{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-watch-sh
data:
{{ (tpl (.Files.Glob "files/jobs/cluster-watch.sh").AsConfig . ) | indent 4 }}
{{- end }}