{{- if .Values.datanode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.datanode.name }}-hostgroup
data:
  datanode-hostgroup.json: |
{{ .Files.Get "files/datanode/datanode-hostgroup.json" | indent 4}}
{{- end }}
