{{- if .Values.datanode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.datanode.componentName }}-krb5-conf
data:
{{ (tpl (.Files.Glob "files/datanode/krb5.conf").AsConfig . ) | indent 4 }}
{{- end }}

