{{- if .Values.datanode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.datanode.componentName }}-pre
data:
  data-pre.sh: |
{{ .Files.Get "files/datanode/data-pre.sh" | indent 4}}
{{- end }}
