{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-pre
data:
  postgres-pre.sh: |
{{ .Files.Get "files/postgres/postgres-pre.sh" | indent 4}}
{{- end }}
