{{- if .Values.postgres.enabled }}
{{- if and .Values.postgres.enabled .Values.postgres.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.name }}-pvc
  labels:
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: {{ .Values.postgres.persistentVolume.storageClassName }}
  accessModes: 
  - {{ .Values.postgres.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistentVolume.storage }}
{{- end }}
{{- end }}
