{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-start
data:
  postgres-start.sh: |
{{ .Files.Get "files/postgres/postgres-start.sh" | indent 4}}
{{- end }}
