{{- if .Values.edgenode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.edgenode.componentName }}-krb5-conf
data:
{{ (tpl (.Files.Glob "files/edgenode/krb5.conf").AsConfig . ) | indent 4 }}
{{- end }}
