{{- if .Values.edgenode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.edgenode.componentName }}-pre
data:
  edge-pre.sh: |
{{ .Files.Get "files/edgenode/edge-pre.sh" | indent 4}}
{{- end }}
