{{- if .Values.edgenode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.edgenode.componentName }}-init
data:
  edge-init.sh: |
{{ .Files.Get "files/edgenode/edge-init.sh" | indent 4}}
{{- end }}
