{{- if .Values.edgenode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.edgenode.componentName }}-ssh-config
data:
{{ (.Files.Glob "files/edgenode/edge-ssh-config.sh").AsConfig | indent 4 }}
{{- end }}
