{{- if .Values.masternode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.masternode.componentName}}-start
data:
  master-start.sh: |
{{ .Files.Get "files/masternode/master-start.sh" | indent 4}}
{{- end }}
