{{- if .Values.masternode.enabled }}
{{- if and .Values.masternode.enabled .Values.masternode.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.masternode.componentName }}-keytab-pvc
  labels:
    app: {{ .Values.masternode.componentName }}-node
spec:
  storageClassName: {{ .Values.masternode.persistentVolume.storageClassName }}
  accessModes:
  - {{ .Values.masternode.persistentVolume.accessModes }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}
