{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ambariserver.componentName }}-hostsupdate
data:
{{ (tpl (.Files.Glob "files/ambari/hostsUpdate.sh").AsConfig . ) | indent 4 }}
{{- end }}