{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ambariserver.componentName }}-krb5-conf
data:
{{ (tpl (.Files.Glob "files/ambari/krb5.conf").AsConfig . ) | indent 4 }}
{{- end }}

