{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ambariserver.componentName}}-start
data:
  ambari-start.sh: |
{{ .Files.Get "files/ambari/ambari-start.sh" | indent 4}}
{{- end }}
