{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ambariserver.componentName }}-blueprint-hdfsyarn
data:
{{ (tpl (.Files.Glob "files/ambari/hdfsyarn.json").AsConfig . ) | indent 4 }}
{{- end }}
