{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ambariserver.componentName }}-pre
data:
  ambari-pre.sh: |
{{ .Files.Get "files/ambari/ambari-pre.sh" | indent 4}}
{{- end }}
