{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ambariserver.componentName }}-hostgroup-hdfs
data:
{{ (tpl (.Files.Glob "files/ambari/hdfs.json").AsConfig . ) | indent 4 }}
{{- end }}
