{{- if .Values.ambariserver.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.ambariserver.componentName }}-keytab-pvc
  labels:
    app: {{ .Values.ambariserver.name }}
spec:
  storageClassName: {{ .Values.ambariserver.persistentVolume.storageClassName }}
  accessModes:
  - {{ .Values.ambariserver.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.ambariserver.persistentVolume.storage }}
{{- end}}
